### ISSUE TITLE
Getting a lot of buffer underruns 

### ISSUE THREAD

**Issue by hanslammerts** [qradiolink/qradiolink#110]
Qradiolink usually is performing ok, but every now and then I see a lot of these messages : 

**ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred**

and you can hear the audio stuttering.
I do not know where to look or how to solve this problem.
Anyone any ideas, please ?

Environment:
Debian 11
Memory 8 GB
6 core Intel i5-8400

**Comment by kantooon** [comment]
I assume this is an ALSA only system. Have you configured $HOME/.asoundrc as outlined in the operation manual?
Anyway, using Pulseaudio - and the relevant sinks and sources - is recommended if you can. Qt audio APIs support ALSA but a lot of the low level details are abstracted away and can't really be configured.
