### ISSUE TITLE
qradiolink.org domain does not resolve - web site unavailable

### ISSUE THREAD

**Issue by jschiefer** [qradiolink/qradiolink#111]
My apologies for the unusual way to report this, but the qradiolink.org website appears to have vanished. The whois record for qradiolink.org shows that the name servers for the domain are ns[12].qradiolink.org. I don't think this could possibly work - the domain name servers cannot be on the domain that you are trying to resolve. The entries should probably point to the name servers of the provider who hosts the web site.

**Comment by kantooon** [comment]
Oh, no worries, and thanks for letting me know. A hardware upgrade that went slightly wrong + me thinking I'd have the time to fix it during weekends (which I didn't).
For now, I've reverted to the old NS records and the site should be reachable again.
