### ISSUE TITLE
Rename QRadioLink desktop icon

### ISSUE THREAD

**Issue by AsciiWolf** [qradiolink/qradiolink#125]
The desktop [icon](https://github.com/qradiolink/qradiolink/blob/next/src/res/icon.png) file name (and its Icon field in [qradiolink.desktop](https://github.com/qradiolink/qradiolink/blob/next/qradiolink.desktop))  is currently just "icon". This is not correct and will cause many issues on a standard Unix-like system when installed system-wide. Please, change the icon file name to a standard "qradiolink".

**Comment by kantooon** [comment]
Ok, thanks for letting me know. It's not very clear to me if the filename needs to be changed from icon.png -> qradiolink.png and if qradiolink.desktop needs an entry like Icon=qradiolink or needs to be Icon=qradiolink.png
I'd appreciate if you could clarify, thanks!

**Comment by AsciiWolf** [comment]
The icon name should always be without extension. The only exception is if a full icon path is specified.
