### ISSUE TITLE
FreeBSD port

### ISSUE THREAD

**Issue by luzpaz** [qradiolink/qradiolink#38]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240534

**Comment by kantooon** [comment]
The `next` branch is based on GNU radio 3.8 now so the port can be attempted. Hover they might hit a problem elsewhere, because video capture still uses V4L2. I can see lots of #ifdefs being needed.

**Comment by kantooon** [comment]
no action, closing
