### ISSUE TITLE
Question about Gnuradio flowgraph used for QPSK modulation

### ISSUE THREAD

**Issue by Radiomix2000** [qradiolink/qradiolink#57]
Hi Kantooon!
First of all, thank you for your work, this is the awesome digital voice SDR software.
I would like to ask you about flowgraph used for QPSK mode. Can you show it?
Just beginning from the audio source and ending by SDR sink? Would like to make some simulations in gnuradio. I'm doing some research regarding to FEC and SNR, and will appreciate your help with this flowgraph.

**Comment by kantooon** [comment]
Thanks fot he kind words. The flowgraph is modular. There is a base flowgraph containing the source (frame data vector) and sink and mode switching logic implemented in https://github.com/kantooon/qradiolink/blob/next/gr/gr_mod_base.cpp
The DQPSK modulator is implemented in https://github.com/kantooon/qradiolink/blob/next/gr/gr_mod_qpsk_sdr.cpp
Framing is done outside of GNU radio, as well as Codec2 or Opus encoding. The same is valid for the demodulator. https://github.com/kantooon/qradiolink/blob/next/gr/gr_modem.cpp contains most of the framing and deframing logic.
In the future, framing and deframing might be moved inside GNU radio custom blocks to give them their own threads and make the modem more customizable.
