### ISSUE TITLE
telnet doesn't work properly...

### ISSUE THREAD

**Issue by moradi655** [qradiolink/qradiolink#69]
Dear Qradiolink Team,
Thank you very much for this wonderful software.

telnet doesn't work in RX mode & can't shown the receiving data from antenna. update plz...????

Sincerely,
M.M

**Comment by kantooon** [comment]
Sorry, closed ticket by mistake. I managed to reproduce it. Next time, please provide a more detailed description of the issue.

**Comment by kantooon** [comment]
Fix is in 0.8.3-3
