### ISSUE TITLE
Settings are corrupted when initialising flowgraph

### ISSUE THREAD

**Issue by kantooon** [qradiolink/qradiolink#79]
**Describe the bug**
Settings are corrupted when the flowgraph is initialised

**To Reproduce**
Edit rx_freq_correction or tx_freq_correction

**Expected behavior**
Settings are not corrupted

**Screenshots**

**Desktop (please complete the following information):**
Any

**Additional context**
Likely caused by removal of gr-osmosdr code for adjusting freq correction and writing custom code

**Comment by alphafox02** [comment]
Sorry I haven’t gotten back to you. Hope to find some time later this week to do some more testing. I did quickly check to make sure my user had the video group, it did, but I wasn’t able to get video. I’m glad you see the issue I was mentioning. I thought it was just something I was doing. Had me confused at first.
