### ISSUE TITLE
Передача во всем диапазоне частот

### ISSUE THREAD

**Issue by rv9ciq** [qradiolink/qradiolink#83]
Hello! The question is how to make the transmitter work in the entire frequency range

**Comment by kantooon** [comment]
There is a checkbox called Limits in the settings page, useful when you're outside the IARU region 1 bandplan.

**Comment by rv9ciq** [comment]
Thank you so much for your hard work on creating this project. And for the help provided. Thanks!!!

**Comment by kantooon** [comment]
You're welcome!
